# Generated by Django 2.0.5 on 2018-07-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('body', models.CharField(max_length=5000)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('s', 'submitted'), ('r', 'rejected'), ('a', 'approved')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('company_name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('P', 'Project Fund'), ('S', 'Student Fund')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=256)),
                ('bio', models.CharField(max_length=2000)),
                ('twitter', models.CharField(max_length=30)),
                ('instagram', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('training_type', models.CharField(choices=[('M', 'masonary'), ('C', 'cooking'), ('T', 'technology')], max_length=256)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Trainer')),
            ],
        ),
    ]
