# Generated by Django 2.0.5 on 2018-07-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180730_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='bio',
            field=models.TextField(max_length=3000),
        ),
    ]
