# Generated by Django 2.0.5 on 2018-07-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180730_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
