# Generated by Django 2.0.5 on 2018-07-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180730_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='facebook',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='twitter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
