# Generated by Django 2.0.5 on 2018-08-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180801_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='vid',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
