# Generated by Django 2.0.4 on 2018-08-23 23:54

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180802_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='article',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='training',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='vid',
        ),
        migrations.AddField(
            model_name='activity',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
