# Generated by Django 2.0.4 on 2018-08-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180824_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
